platform:
  - x86
environment:
  global:
    APPVEYOR_OS_NAME: windows
    GOPATH: c:\gopath
    CGO_ENABLED: 1
    GOOS: windows
  matrix:
    - MSYS2_ARCH: i686
      MSYS2_BITS: 32
      MSYSTEM: MINGW32
      METHOD: cross
      MSYS2_BASEVER: 20150916
      GOARCH: 386

cache: 
  - 'msys2-base-%MSYS2_ARCH%-%MSYS2_BASEVER%.tar.xz'
clone_folder: c:\gopath\src\github.com\dh1tw\gorigctl
clone_script:
    - cmd: git clone --recursive -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    - cmd: cd %APPVEYOR_BUILD_FOLDER%
    - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
    - cmd: git submodule update --init --recursive
    - cmd: git fetch --tags
install:
  - .\ci\install-deps-windows.bat
  - echo %GOOS%
  - echo %GOARCH%
  - cmd: SET PATH=%PATH%;/c/gopath/bin;/c/gopath/bin/windows_386
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/dh1tw/gorigctl && go get -v ./..."'
  - '%MSYS_PATH%\usr\bin\bash -lc "go get -v github.com/gogo/protobuf/protoc-gen-gofast"'
  
build_script:
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/dh1tw/gorigctl && make dist"'
after_build:
  - .\ci\build-windows-bundle.bat
artifacts:
  - path: '*.zip'
    name: gorigctl
deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: oXpR35KilKmCCTVxxMaP6NR5t1K3i9517pnZE+JHqSshD4A+z0Svdj16r/8kIEJ7
  artifact: gorigctl            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only