[credentials]
username = ""
password = ""

[mqtt]
broker-url = "test.mosquitto.org"
broker-port = 1883
station = "remoteStation"
radio = "ft2000"

[radio]
rig-model = 1 #Dummy
#rig-model = 128 #FT-950
#rig-model = 228 #TS-480
#rig-model = 123 #TS-879
#rig-model = 122 #FT-857
baudrate = 38400
portname = "/dev/mhuxd/cat"
databits = 8
stopbits = 1
parity = "none"
handshake = "none"
hl-debug-level = 1
polling-interval = "200ms"
sync-interval = "3s"